Hatiralar.WebUII/Models/ErrorViewModel.cs
using System;

namespace Hatiralar.WebUII.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hatiralar.WebUII/Controllers/AuthController.cs
using Hatiralar.Businees.Abstract;
using Hatiralar.Entities.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Hatiralar.WebUII.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet] //Sadeece Görüntüyü Vericek, Post isteğini, AJAX ile Apiye göndereceğiz.
        public IActionResult Register()
        {
            return View();
        }

        [HttpGet] //Sadeece Görüntüyü Vericek, Post isteğini AJAX ile Apiye göndereceğiz.
        public IActionResult Login()
        {
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> Register(RegisterDto registerDto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _authService.UserRegister(registerDto);
        //        return RedirectToAction("/Auth/Login");
        //    }
        //    ModelState.AddModelError("", "Üyelik işlemi başarısız.");
        //    return View(registerDto);
        //}



        //[HttpPost]
        //public async Task<IActionResult> Login(LoginDto loginDto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _authService.Login(loginDto);
        //        return RedirectToAction("yönlendirilecek sayfa");
        //    }
        //    ModelState.AddModelError("", "Kullanıcı adı veya parola hatalı");
        //    return View(loginDto);
        //}
    }
}

Hatiralar.WebUII/Controllers/AuthhController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hatiralar.WebUII.Controllers
{
    public class AuthhController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
    }
}

Hatiralar.WebUII/Controllers/HomeController.cs
using Hatiralar.WebUII.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hatiralar.WebUII.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hatiralar.WebUII/Views/Authh/Login.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="style.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

    <title>Admin</title>
</head>
<body>
    <div class="container">
        <div class="row main">
            <div class="main-login main-center">
                <form method="post" asp-action="Login" asp-controller="Auth">
                    <div class="text-center" asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label for="email" class="cols-sm-2 control-label">Email</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="Email" id="Email" placeholder="Mail adresini gir" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="cols-sm-2 control-label">Password</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                <input type="password" class="form-control" name="Password" id="Password" placeholder="Enter your Password" />
                            </div>
                        </div>
                    </div>
                    <button type="submit">Giriş</button>

                </form>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script>
        $(document).ready(function() {
            $("form").submit(function(event) {
                var formData = {
                    Email: $("#Email").val(),
                    Password: $("#Password").val()
                };
                $.ajax({
                    type: "POST",
                    url: "http://localhost:37551/Members/Login",
                    data: formData,
                    success: (response) => {
                        if (response == "Kullanıcı adı veya parola hatalı") {
                            alert("Kullanıcı Adı veya parolanız hatalı")
                        }
                        else {
                            windows.localStorage.setItem("token", "Bearer" + response)
                            windows.location.href = "/Home/Index"
                        }
                    },
                    error: x => {
                        alert("Sunucuya ulaşılamadı. Statü Kodu = " + x.status)
                    }
                })
                event.preventDefault();
            });
        });
    </script>
</body>
</html>

Hatiralar.WebUII/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div id="login">

    </div>
    <h1>Burası Anasayfa</h1>

    <h1>Burası Şehirler</h1>
    <table class="table table-active">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created Date</th>
            </tr>
        </thead>
        <tbody id="cities">

        </tbody>
    </table>
</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

<script>
function getCities() {
  const citiesElement = $("#cities")
    $.ajax({
      type:"GET",
      url : "http://localhost:37551/api/Cities",
      headers: {"Authorization" : localStorage.getItem('token')},
      contentType : "application/json",
        success: (responseData) => {
            console.log("hata varmı?")
            $.each(responseData, function(index, value) {
                citiesElement.append(
                    `
                  <tr>  
                     <td>${value.id}</td>
                     <td>${value.name}</td>
                     <td>${value.createDate}</td>
                  </tr>
                `
                )
            })
        },
        error: (error) => { 
            console.log("hata varmı?")
            if (error.status == "401") {
               citiesElement.append("Veriye erişiminiz yok.");
            }
        }
    })
}
getCities()

//$(document).ready(
//function getCities() {
//  const citiesElement = $("#cities")
//    $.ajax({
//      type:"GET",
//      url : "http://localhost:37551/api/Cities",
//      headers: {"Authorization" : localStorage.getItem('token')},
//      contentType : "application/json",
//        success: (responseData) => {
//            console.log("hata varmı?")
//            $.each(responseData, function(index, value) {
//                citiesElement.append(
//                    `
//                  <tr>  
//                     <td>${value.id}</td>
//                     <td>${value.name}</td>
//                     <td>${value.createDate}</td>
//                  </tr>
//                `
//                )
//            })
//        },
//        error: (error) => { 
//            console.log("hata varmı?")
//            if (error.status == "401") {
//               citiesElement.append("Veriye erişiminiz yok.");
//            }
//        }
//    })
//})

function getExistButton() { 
     var existToken = window.localStorage.getItem('token')
    if (!(existToken == null || existToken == "")) {
        $("#login").append(`<button class="btn btn-danger" onclick="signOut()">Çıkış Yap </button>`);
    }
    else {
        $("#login").append(`<button class="btn btn-primary" onclick="signOut()">Giriş Yap </button>`);
    }
}
getExistButton();

function signOut() { 
   window.localStorage.removeItem('token')
   window.location.href = "/Auth/Login"
}
   
</script>

Hatiralar.WebUII/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hatiralar.WebUII</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hatiralar.WebUII</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Hatiralar.WebUII - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>